# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

# Enable navigation with vi keys
setw -g mode-keys vi
set -g status-keys vi

#set -g default-terminal "screen-256color"
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set-option -g focus-events on


# remap prefix to Control + q
set -g prefix C-q
# bind 'C-q C-q' to type 'C-q'
bind C-q send-prefix
unbind C-b

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# Set the base index for windows to 1 instead of 0.
set -g base-index 1

# Set the base index for panes to 1 instead of 0.
setw -g pane-base-index 1

set -sg escape-time 0
set-option -g history-limit 50000

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n C-h if-shell "$is_vim" "send-keys C-h"  "select-pane -L"
bind-key -n C-j if-shell "$is_vim" "send-keys C-j"  "select-pane -D"
bind-key -n C-k if-shell "$is_vim" "send-keys C-k"  "select-pane -U"
bind-key -n C-l if-shell "$is_vim" "send-keys C-l"  "select-pane -R"
#bind-key -n C-\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"
bind-key -T copy-mode-vi C-h select-pane -L
bind-key -T copy-mode-vi C-j select-pane -D
bind-key -T copy-mode-vi C-k select-pane -U
bind-key -T copy-mode-vi C-l select-pane -R
#bind-key -T copy-mode-vi C-\ select-pane -l

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

bind C-q send-prefix
bind q last-window
bind C-q last-window

bind C-p previous-window
bind C-n next-window

bind "<" swap-window -d -t -1
bind ">" swap-window -d -t +1

bind "H" join-pane -bh
bind "J" join-pane -v
bind "K" join-pane -bv
bind "L" join-pane -h

# vi mode
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel\; run "tmux save -|xclip -sel clip >/dev/null 2>&1"
#bind-key -T copy-mode-vi y send -X copy-selection-and-cancel
#bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel
unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode after dragging with mouse

bind-key a set-window-option synchronize-panes\; display-message "synchronize-panes is now #{?pane_synchronized,on,off}"

set -g @catppuccin_flavor 'mocha' # latte, frappe, macchiato or mocha
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_text " #W"
set -g @thm_mauve "#ba8af5"

# Load catppuccin
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
#set -g @plugin 'omerxx/catppuccin-tmux'

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"

set-option -g default-shell /bin/zsh

set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-processes '"dmesg -HwT"'
set -g @resurrect-capture-pane-contents 'on'

run '~/.tmux/plugins/tpm/tpm'
