preload = /home/john/.config/hypr/arch2.jpg

wallpaper = DP-1,/home/john/.config/hypr/arch2.jpg
wallpaper = eDP-1,/home/john/.config/hypr/arch2.jpg
wallpaper = HDMI-A-1,/home/john/.config/hypr/arch2.jpg
wallpaper = DP-3,/home/john/.config/hypr/arch2.jpg

#enable splash text rendering over the wallpaper
splash = false

#fully disable ipc
ipc = off
